"""Build data/sources/sources.seed.yaml from discovery evidence and the feed selection.

Every URL and evidence link comes from data/sources/discovery.json; nothing is typed by hand.
Ownership and ratings stay empty: they need evidence that feed discovery does not provide.

Usage: uv run python -m lens.ingest.seedgen
"""

from __future__ import annotations

import json
import sys
from typing import Any

import yaml

from lens.core.settings import REPO_ROOT

HEADER = """\
# GENERATED by `make seed-gen` from data/sources/discovery.json + data/sources/feed_selection.yaml.
# Edit those inputs, not this file. See docs/13_INDIA_SOURCES.md.
# Ownership and ratings are intentionally empty: they need evidence URLs (rule 7).
"""


def build() -> list[dict[str, Any]]:
    data = REPO_ROOT / "data/sources"
    discovery: dict[str, Any] = json.loads((data / "discovery.json").read_text(encoding="utf-8"))
    selection = yaml.safe_load((data / "feed_selection.yaml").read_text(encoding="utf-8"))
    candidates = yaml.safe_load((data / "candidates.yaml").read_text(encoding="utf-8"))
    langs = {"english": "en", "hindi": "hi"}
    cand = {c["slug"]: (c, c.get("language") or langs.get(group)) for group, cs in candidates.items() for c in cs}

    out: list[dict[str, Any]] = []
    for slug, (c, lang) in cand.items():
        d = discovery.get(slug)
        if d is None:
            raise SystemExit(f"{slug}: no discovery record; run `make discover-feeds {slug}`")
        chosen = selection["selected"].get(slug)
        inactive_reason = selection.get("inactive", {}).get(slug)
        if not chosen and not inactive_reason:
            raise SystemExit(f"{slug}: neither selected nor marked inactive in feed_selection.yaml")
        by_url = {f["url"]: f for f in d["feeds"]}
        feeds = []
        for url in chosen or []:
            f = by_url.get(url)
            if f is None or not f["parsed"] or not f["items"] or not f["robots_allowed"]:
                raise SystemExit(f"{slug}: {url} is not a usable feed in discovery.json")
            feeds.append(
                {
                    "url": url,
                    "kind": "sitemap" if f.get("kind") == "sitemap" else "rss",
                    "topic": None,
                    "evidence_url": f["found_on"],
                    "found_via": f["how"],
                    "checked_at": d["checked_at"],
                }
            )
        # The URL we tried: final URLs can be geo-redirects (e.g. an edition for the crawler's country).
        homepage = c["homepage"]
        robots_status = d.get("robots_status")
        # Conservative: a robots.txt we could not read (any 4xx/5xx, incl. 403 blocks) is not permission.
        robots_ok = bool(d.get("homepage_robots_allowed")) and robots_status is not None and robots_status < 400
        out.append(
            {
                "slug": slug,
                "name": c["name"],
                "homepage_url": homepage,
                "language_codes": [lang],
                "region": "national" if lang in ("en", "hi") else "MH",
                "is_wire": False,
                "is_fact_checker": False,
                "license_mode": "snippet_only",
                # Feed thumbnails are hotlinked (never re-hosted) only where the owner allowed it (ADR-0034).
                "image_policy": "hotlink" if slug in selection.get("image_hotlink", []) and feeds else "none",
                "robots_ok": robots_ok,
                "active": bool(feeds) and not inactive_reason,
                "inactive_reason": inactive_reason,
                "feed_urls": feeds,
                "inclusion_reason": (
                    "Named by the project owner on 2026-09-21. Machine-readable access verified on the "
                    "outlet's own site (see feed evidence). "
                    "Review against the published selection criteria pending."
                    if feeds
                    else "Named by the project owner on 2026-09-21. Kept inactive: see inactive_reason."
                ),
                "evidence": {
                    "feed_evidence_url": feeds[0]["evidence_url"] if feeds else None,
                    "robots_url": d.get("robots_url"),
                    # First homepage link mentioning "terms"; a person must confirm it is the site's terms.
                    "terms_link_found": d.get("terms_url"),
                    "terms_evidence_url": "TO_VERIFY",
                },
                "ownership": [],
                "ratings": [],
            }
        )
    return out


def main() -> int:
    seed = build()
    path = REPO_ROOT / "data/sources/sources.seed.yaml"
    body = yaml.safe_dump(seed, allow_unicode=True, sort_keys=False, width=110)
    path.write_text(HEADER + body, encoding="utf-8")
    active = [s for s in seed if s["active"]]
    print(f"wrote {path.relative_to(REPO_ROOT)}: {len(active)} active, {len(seed) - len(active)} inactive")
    return 0


if __name__ == "__main__":
    sys.exit(main())
