"""Migrations apply cleanly on an empty database, reverse fully, and match the models."""

import uuid
from collections.abc import Iterator

import pytest
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import create_engine, inspect, text
from sqlalchemy.engine import make_url

from alembic import command
from lens.core.settings import REPO_ROOT, get_settings
from lens.db.models import Base

pytestmark = pytest.mark.db


@pytest.fixture
def empty_db_url() -> Iterator[str]:
    base = make_url(get_settings().database_url)
    admin = create_engine(base.set(database="postgres"), isolation_level="AUTOCOMMIT")
    name = f"lens_test_{uuid.uuid4().hex[:8]}"
    try:
        with admin.connect() as conn:
            conn.execute(text(f'CREATE DATABASE "{name}"'))
    except Exception as exc:  # pragma: no cover - environment dependent
        pytest.skip(f"Postgres not reachable ({exc.__class__.__name__}); run `make up`")
    try:
        yield base.set(database=name).render_as_string(hide_password=False)
    finally:
        with admin.connect() as conn:
            conn.execute(text(f'DROP DATABASE IF EXISTS "{name}" WITH (FORCE)'))
        admin.dispose()


def _alembic_config(url: str) -> Config:
    cfg = Config(str(REPO_ROOT / "backend" / "alembic.ini"))
    cfg.set_main_option("sqlalchemy.url", url)
    return cfg


def test_upgrade_downgrade_roundtrip(empty_db_url: str) -> None:
    cfg = _alembic_config(empty_db_url)
    command.upgrade(cfg, "head")

    engine = create_engine(empty_db_url)
    try:
        assert set(Base.metadata.tables) <= set(inspect(engine).get_table_names())
        try:
            command.check(cfg)
        except AutogenerateDiffsDetected as exc:
            pytest.fail(f"models and migrations have drifted: {exc}")

        command.downgrade(cfg, "base")
        with engine.connect() as conn:
            tables = set(inspect(conn).get_table_names()) - {"alembic_version"}
            enums = conn.execute(text("select count(*) from pg_type where typtype = 'e'")).scalar()
        assert tables == set()
        assert enums == 0
    finally:
        engine.dispose()
