"""Deterministic keyword topic rules for stories (English, Hindi, Marathi).

Stories are tagged by `lens.nlp.topic_embed`, which uses these rules only to pick seed
stories for its topic prototypes; the rules alone are too noisy to tag the feed.

Rules are keyword-sets keyed by topic slug; each key is matched against the
headline (and, for Hindi/Marathi, also the snippet). The first topic whose
intersection is non-empty wins. Order matters: more specific topics are listed
first so they take priority over broad catch-all topics like "world".

Topics match the frontend fixture list (docs/10) so the rail / topic pages
show consistent slugs: top, politics, business, world, sports, tech, health,
science, entertainment. "top" is excluded here — the feed already has it as a
tab; a story's topic is its *subject*, not the home-tab alias.
"""

from __future__ import annotations

import re
import uuid
from collections import Counter, defaultdict

from sqlalchemy import select
from sqlalchemy.orm import Session

from lens.db.models import Article, StoryArticle

# --------------------------------------------------------------------------- rules
# Each rule is a list of unicode-normalised lowercase word forms. We run them
# through _tokenise so compound Hindi/Marathi headlines still match on individual
# words (the regex already keeps Indic combining marks inside tokens, ADR-09).
#
# ponytail: this could be promoted to a config file later; the list is small
# enough to stay inline and avoids an extra source of truth.

_POLITICS = [
    # English
    "election",
    "vote",
    "voting",
    "prime minister",
    "chief minister",
    "cm",
    "parliament",
    "lok sabha",
    "rajya sabha",
    "congress",
    "bjp",
    "ais",
    "aipcc",
    "modi",
    "rahul",
    "gandhi",
    "shiv sena",
    "shivsena",
    "samajwadi",
    "bsp",
    "cabinet",
    "minister",
    "mla",
    "mp",
    "by-election",
    "by poll",
    "seat",
    "constituency",
    "polling",
    "neta",
    "sarkar",
    "government",
    "coalition",
    "alliance",
    "nda",
    "india alliance",
    # Hindi
    "चुनाव",
    "मतदान",
    "मतदाता",
    "मंत्री",
    "मन्त्री",
    "मुख्यमंत्री",
    "संसद",
    "लोकसभा",
    "राज्यसभा",
    "कांग्रेस",
    "भाजपा",
    "मोदी",
    "विधानसभा",
    "विधायक",
    "उप चुनाव",
    "उप चूंनाव",
    "सरकार",
    "गठबंधन",
    "आरक्षण",
    "विपक्ष",
    "सत्ता",
    "उम्मीदवार",
    "उमेदवार",
    "अंतर्राष्ट्रीय",
    "विदेश",
    "विदेश मंत्री",
    # Marathi
    "निवडणूक",
    "मतदान",
    "मंत्री",
    "मुख्यमंत्री",
    "संसद",
    "काँग्रेस",
    "भाजपा",
    "विधानसभा",
    "विधायक",
    "सरकार",
    "गठबंधन",
    "उमेदवार",
    "विदेश",
]

_BUSINESS = [
    "rupee",
    "inr",
    "stock",
    "bse",
    "nse",
    "sensex",
    "nifty",
    "share",
    "shares",
    "market",
    "trade",
    "trading",
    "business",
    "company",
    "corporation",
    "start-up",
    "startup",
    "founder",
    "ceo",
    "cfo",
    "profit",
    "loss",
    "revenue",
    "turnover",
    "market cap",
    "ipo",
    "listing",
    "rbi",
    "reserve bank",
    "inflation",
    "gdp",
    "fiscal",
    "budget",
    "tax",
    "gst",
    "subsidy",
    "export",
    "import",
    "supply chain",
    # Hindi
    "रूपया",
    "रुपया",
    "रु.",
    "रुपैया",
    "भारतीय रुपये",
    "शेयर",
    "शेयर बाज़ार",
    "बजार",
    "व्यापार",
    "कंपनी",
    "लाभ",
    "हानि",
    "मुनाफा",
    "नुकसान",
    "शेयर बाज़ार",
    "स्टॉक",
    "आईपीओ",
    "आरबीआई",
    "भारतीय रिज़र्व बैंक",
    "मुद्रास्फीति",
    "महंगाई",
    "महँगाई",
    "जीडीपी",
    "घरेलू उत्पाद",
    "बजट",
    "जीएसटी",
    "आयात",
    "निर्यात",
    "रोज़गार",
    "रोज़गार",
    # Marathi
    "रूपये",
    "रुपये",
    "शेअर",
    "शेअर बाजार",
    "व्यवसाय",
    "कंपनी",
    "नफा",
    "तोटा",
    "आईपीओ",
    "आरबीआई",
    "महागाई",
    "गुंतवणूक",
]

_WORLD = [
    "usa",
    "united states",
    "white house",
    "pentagon",
    "state department",
    "senate",
    "trump",
    "biden",
    "obama",
    "clinton",
    "china",
    "beijing",
    "taiwan",
    "tibet",
    "pakistan",
    "islamabad",
    "bangladesh",
    "dhaka",
    "afghanistan",
    "kabul",
    "srilanka",
    "sri lanka",
    "colombo",
    "nepal",
    "kathmandu",
    "bhutan",
    "thimphu",
    "maldives",
    "russia",
    "moscow",
    "kremlin",
    "putin",
    "uk",
    "united kingdom",
    "britain",
    "london",
    "europe",
    "brussels",
    "european union",
    "eu",
    "nato",
    "middle east",
    "israel",
    "palestine",
    "gaza",
    "hamas",
    "netanyahu",
    "iran",
    "tehran",
    "iraq",
    "baghdad",
    "syria",
    "damascus",
    "yemen",
    "houthi",
    "africa",
    "nigeria",
    "kenya",
    "japan",
    "tokyo",
    "south korea",
    "seoul",
    "australia",
    "canada",
    # Hindi
    "अमेरिका",
    "अमेरिकी",
    "ट्रंप",
    "बाइडेन",
    "पाकिस्तान",
    "चीन",
    "रूस",
    "यूनाइटेड किंगडम",
    "ब्रिटेन",
    "लंदन",
    "इज़राइल",
    "फिलीस्तीन",
    "गाजा",
    "ईरान",
    "मध्य पूर्व",
    "जापान",
    "कोरिया",
    "ऑस्ट्रेलिया",
    "कनाडा",
    # Marathi
    "अमेरिका",
    "अमेरिकी",
    "त्रम्प",
    "बायडेन",
    "पाकिस्तान",
    "चीन",
    "रशिया",
    "ब्रिटन",
    "इस्रायल",
    "फिलिस्तीन",
    "गाझा",
    "इराण",
    "मध्य पूर्व",
]

_SPORTS = [
    "cricket",
    "ipl",
    "bcci",
    "icc",
    "test match",
    "wicket",
    "batting",
    "bowling",
    "innings",
    "run chase",
    "football",
    "soccer",
    "premier league",
    "champions league",
    "fifa",
    "olympics",
    "olympic",
    "commonwealth games",
    "asian games",
    "world cup",
    "t20",
    "odi",
    "t10",
    "hockey",
    "badminton",
    "tennis",
    "athletics",
    "swimming",
    "wimbledon",
    "grand slam",
    "sachin",
    "kohli",
    "dhoni",
    "virat",
    "rohit",
    "pant",
    "jadeja",
    "bumrah",
    "ashwin",
    # Hindi
    "क्रिकेट",
    "आईपीएल",
    "बीसीसीआई",
    "ओलंपिक",
    "ऑलिम्पिक",
    "फुटबॉल",
    "वर्ल्ड कप",
    "एशियन गेम्स",
    # Marathi
    "क्रिकेट",
    "ऑलिम्पिक",
    "फुटबॉल",
    "वर्ल्ड कप",
]

_TECH = [
    "ai",
    "artificial intelligence",
    "machine learning",
    "deep learning",
    "chatbot",
    "chat gpt",
    "gpt",
    "openai",
    "claude",
    "gemini",
    "llm",
    "large language model",
    "transformer",
    "neural network",
    "quantum",
    "quantum computing",
    "software",
    "app",
    "application",
    "android",
    "ios",
    "iphone",
    "startup",
    "founder",
    "venture capital",
    "funding",
    "series a",
    "cybersecurity",
    "hacking",
    "data breach",
    "ransomware",
    "blockchain",
    "crypto",
    "bitcoin",
    "ethereum",
    "web3",
    "metaverse",
    "cloud",
    "aws",
    "azure",
    "google cloud",
    "semiconductor",
    "chip",
    "processor",
    "intel",
    "amd",
    "nvidia",
    "tesla",
    "ev",
    "electric vehicle",
    "self driving",
    "autonomous",
    "robot",
    "robotics",
    "5g",
    "6g",
    "satellite",
    "starlink",
    # Hindi
    "तकनीक",
    "प्रौद्योगिकी",
    "आर्टिफिशियल इंटेलिजेंस",
    "एआई",
    "सॉफ्टवेयर",
    "ऐप",
    "मोबाइल",
    "डिजिटल",
    "इंटरनेट",
    "स्टार्टअप",
    "कंपनी",
    "चिप",
    "सेमीकंडक्टर",
    "क्लाउड",
    # Marathi
    "तंत्रज्ञान",
    "प्रौद्योगिकी",
    "सॉफ्टवेअर",
    "अॅप",
    "मोबाईल",
    "डिजिटल",
    "इंटरनेट",
    "स्टार्टअप",
    "कंपनी",
    "क्लाउड",
]

_HEALTH = [
    "vaccine",
    "vaccination",
    "covid",
    "coronavirus",
    "sars-cov-2",
    "flu",
    "influenza",
    "disease",
    "illness",
    "hospital",
    "patient",
    "doctor",
    "surgeon",
    "medicine",
    "pharma",
    "drug",
    "prescription",
    "cancer",
    "tumor",
    "chemotherapy",
    "radiotherapy",
    "mental health",
    "depression",
    "anxiety",
    "diet",
    "nutrition",
    "fitness",
    "exercise",
    "yoga",
    "diabetes",
    "heart attack",
    "cardiac",
    "stroke",
    "blood pressure",
    "pandemic",
    "epidemic",
    "outbreak",
    "immunization",
    "ayushman",
    "pmjay",
    # Hindi
    "स्वास्थ्य",
    "अस्पताल",
    "डॉक्टर",
    "दवा",
    "वैक्सीन",
    "कोविड",
    "कोरोना",
    "महामारी",
    "बीमारी",
    "रोग",
    "मनोविज्ञान",
    "मानसिक स्वास्थ्य",
    "मानसिक रोग",
    "मधुमेह",
    "हार्ट अटैक",
    "कैंसर",
    # Marathi
    "आरोग्य",
    "रुग्णालय",
    "डॉक्टर",
    "औषध",
    "लस",
    "कोविड",
    "कोरोना",
    "आजार",
    "रोग",
]

_SCIENCE = [
    "nasa",
    "space",
    "rocket",
    "satellite",
    "ISS",
    "iss",
    "moon",
    "mars",
    "solar",
    "planet",
    "galaxy",
    "physics",
    "chemistry",
    "biology",
    "neuroscience",
    "genetics",
    "dna",
    "evolution",
    "fossil",
    "archaeology",
    "ISRO",
    "chandrayaan",
    "research",
    "study",
    "discovery",
    "scientist",
    "laboratory",
    "climate",
    "climate change",
    "global warming",
    "environment",
    "ecology",
    "biodiversity",
    "wildlife",
    "conservation",
    "indian space research organisation",
    "isro",
    # Hindi
    "अंतरिक्ष",
    "चाँद",
    "मंगल",
    "सूरज",
    "ग्रह",
    "तारा",
    "विज्ञान",
    "अन्वेषण",
    "खोज",
    "शोध",
    "प्रयोगशाला",
    "इसरो",
    "चंद्रयान",
    "गगनयान",
    "जलवायु",
    "पर्यावरण",
    "जैव विविधता",
    "वन्य जीव",
    # Marathi
    "अंतरिक्ष",
    "चंद्र",
    "मंगळ",
    "सूर्य",
    "ग्रह",
    "तारा",
    "विज्ञान",
    "अन्वेषण",
    "शोध",
    "प्रयोगशाळा",
    "इस्रो",
    "चंद्रयान",
    "गगनयान",
]

_ENTERTAINMENT = [
    "bollywood",
    "hollywood",
    "movie",
    "film",
    "actor",
    "actress",
    "celebrity",
    "awards",
    "oscars",
    "emmys",
    "grammys",
    "music",
    "song",
    "singer",
    "concert",
    "album",
    "netflix",
    "amazon prime",
    "disney+",
    "hotstar",
    "mx player",
    "web series",
    "ott",
    "comedy",
    "stand-up",
    "kriti",
    "deepika",
    "alia",
    "ranveer",
    "shah rukh",
    "salman",
    "ajay",
    "akshay",
    "srk",
    # Hindi
    "बॉलीवुड",
    "फिल्म",
    "एक्टर",
    "एक्ट्रेस",
    "संगीत",
    "गाना",
    "संगीतकार",
    "कलाकार",
    "पुरस्कार",
    "ऑस्कर",
    "नेटफ्लिक्स",
    "हॉटस्टार",
    "वेब सीरीज़",
    "वेब सीरीज",
    # Marathi
    "बॉलीवुड",
    "चित्रपट",
    "अभिनेता",
    "अभिनेत्री",
    "संगीत",
    "गाणे",
    "कलाकार",
    "पुरस्कार",
    "नेटफ्लिक्स",
    "हॉटस्टार",
]

# Order: specific first, broad last. "top" is intentionally omitted; the UI
# surfaces it as the tab label, not as a story topic.
_RULES: list[tuple[str, list[str]]] = [
    ("sports", _SPORTS),
    ("politics", _POLITICS),
    ("business", _BUSINESS),
    ("tech", _TECH),
    ("health", _HEALTH),
    ("science", _SCIENCE),
    ("entertainment", _ENTERTAINMENT),
    ("world", _WORLD),
]

# Word chars include Devanagari combining marks, which Python's \w misses (ADR-0014).
_W = r"[\w\u0900-\u097F]"


def _pattern(keywords: list[str]) -> re.Pattern[str]:
    alts = sorted({k.strip().lower() for k in keywords if k.strip()}, key=len, reverse=True)
    return re.compile(rf"(?<!{_W})(?:{'|'.join(map(re.escape, alts))})(?!{_W})")


_PATTERNS = [(topic, _pattern(kws)) for topic, kws in _RULES]


def classify(headline: str, snippet: str | None = None, language: str | None = None) -> str | None:
    """Return the first topic (in `_RULES` order) with a whole-word/phrase match, else None."""
    text = f"{headline} {snippet or ''}".lower()
    return next((topic for topic, pat in _PATTERNS if pat.search(text)), None)


# --------------------------------------------------------------------------- backfill


def keyword_votes(session: Session, story_ids: list[str] | None = None) -> dict[uuid.UUID, Counter[str]]:
    """Per story, how many member articles (headline + snippet) each topic's keywords match."""
    q = select(StoryArticle.story_id, Article.title, Article.snippet).join(
        Article, Article.id == StoryArticle.article_id
    )
    if story_ids is not None:
        q = q.where(StoryArticle.story_id.in_([uuid.UUID(s) for s in story_ids]))
    votes: dict[uuid.UUID, Counter[str]] = defaultdict(Counter)
    for sid, title, snippet in session.execute(q):
        if topic := classify(title, snippet):
            votes[sid][topic] += 1
    return votes


def vote_winner(votes: Counter[str]) -> str | None:
    """Most common topic; ties go to `_RULES` order."""
    order = {t: i for i, (t, _) in enumerate(_RULES)}
    return min(votes, key=lambda t: (-votes[t], order[t])) if votes else None
