"""source fetch state

Revision ID: 93a17ceb7100
Revises: 4abec0e0d501
Create Date: 2026-09-21 16:03:42.607678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93a17ceb7100'
down_revision: Union[str, Sequence[str], None] = '4abec0e0d501'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_fetch_state',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('feed_url', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('interval_min', sa.Integer(), server_default=sa.text('15'), nullable=False),
    sa.Column('next_fetch_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('etag', sa.Text(), nullable=True),
    sa.Column('last_modified', sa.Text(), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_items', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_new', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_source_fetch_state_source_id_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source_id', 'feed_url', name=op.f('pk_source_fetch_state'))
    )
    op.add_column('sources', sa.Column('inactive_reason', sa.Text(), nullable=True))
    op.add_column('sources', sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'evidence')
    op.drop_column('sources', 'inactive_reason')
    op.drop_table('source_fetch_state')
    # ### end Alembic commands ###
