"""initial schema

Revision ID: 4abec0e0d501
Revises: 
Create Date: 2026-09-21 12:25:09.517429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4abec0e0d501'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

ENUMS = {
    "license_mode": ("full_text", "snippet_only", "link_only"),
    "image_policy": ("hotlink", "none"),
    "stance": ("critical", "balanced", "supportive", "not_applicable", "unclassified"),
    "stance_target": ("central_govt", "state_govt", "opposition", "none"),
    "confidence": ("low", "medium", "high"),
    "story_status": ("developing", "stable", "archived"),
    "analysis_depth": ("headline_only", "snippet", "full_text"),
}


def upgrade() -> None:
    bind = op.get_bind()
    for name, values in ENUMS.items():
        postgresql.ENUM(*values, name=name).create(bind, checkfirst=True)
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dead_letters',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('stage', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dead_letters'))
    )
    op.create_table('feedback',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('ref_id', sa.UUID(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feedback'))
    )
    op.create_table('guard_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.Column('guard_id', sa.Text(), nullable=False),
    sa.Column('stage', sa.Text(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('score', sa.REAL(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guard_events'))
    )
    op.create_index('ix_guard_events_guard_id_created_at', 'guard_events', ['guard_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('review_queue',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('ref_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='open', nullable=False),
    sa.Column('assigned_to', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_queue'))
    )
    op.create_table('sources',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('homepage_url', sa.Text(), nullable=False),
    sa.Column('language_codes', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('country', sa.Text(), server_default='IN', nullable=False),
    sa.Column('region', sa.Text(), nullable=True),
    sa.Column('feed_urls', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('license_mode', postgresql.ENUM('full_text', 'snippet_only', 'link_only', name='license_mode', create_type=False), server_default='snippet_only', nullable=False),
    sa.Column('image_policy', postgresql.ENUM('hotlink', 'none', name='image_policy', create_type=False), server_default='none', nullable=False),
    sa.Column('robots_ok', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_wire', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_fact_checker', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sources')),
    sa.UniqueConstraint('slug', name=op.f('uq_sources_slug'))
    )
    op.create_table('stories',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('headline_lang', sa.Text(), nullable=False),
    sa.Column('status', postgresql.ENUM('developing', 'stable', 'archived', name='story_status', create_type=False), server_default='developing', nullable=False),
    sa.Column('topic', sa.Text(), nullable=True),
    sa.Column('region', sa.Text(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('article_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('source_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('languages', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('kill_switch', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('review_status', sa.Text(), server_default='auto', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stories')),
    sa.UniqueConstraint('slug', name=op.f('uq_stories_slug'))
    )
    op.create_index('ix_stories_last_updated_at', 'stories', [sa.literal_column('last_updated_at DESC')], unique=False)
    op.create_index('ix_stories_topic_last_updated_at', 'stories', ['topic', sa.literal_column('last_updated_at DESC')], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('consent_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_table('articles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('canonical_url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('analysis_depth', postgresql.ENUM('headline_only', 'snippet', 'full_text', name='analysis_depth', create_type=False), nullable=False),
    sa.Column('language', sa.Text(), nullable=False),
    sa.Column('language_conf', sa.REAL(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('byline', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('simhash', sa.BigInteger(), nullable=True),
    sa.Column('is_news', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_syndicated', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('syndicated_from', sa.Text(), nullable=True),
    sa.Column('original_article_id', sa.UUID(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('entities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('event_type', sa.Text(), nullable=True),
    sa.Column('schema_version', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['original_article_id'], ['articles.id'], name=op.f('fk_articles_original_article_id_articles')),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_articles_source_id_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_articles')),
    sa.UniqueConstraint('canonical_url', name=op.f('uq_articles_canonical_url')),
    sa.UniqueConstraint('source_id', 'url', name=op.f('uq_articles_source_id_url'))
    )
    op.create_index('ix_articles_published_at', 'articles', [sa.literal_column('published_at DESC')], unique=False)
    op.create_index(op.f('ix_articles_simhash'), 'articles', ['simhash'], unique=False)
    op.create_index('ix_articles_source_id_published_at', 'articles', ['source_id', sa.literal_column('published_at DESC')], unique=False)
    op.create_table('ask_turns',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('raw_query', sa.Text(), nullable=False),
    sa.Column('neutral_query', sa.Text(), nullable=True),
    sa.Column('lang', sa.Text(), nullable=True),
    sa.Column('intent', sa.Text(), nullable=True),
    sa.Column('story_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('answer', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('abstained', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('model_versions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prompt_versions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('langsmith_run_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ask_turns_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ask_turns'))
    )
    op.create_table('fact_checks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('claim_reviewed', sa.Text(), nullable=False),
    sa.Column('rating_original', sa.Text(), nullable=True),
    sa.Column('rating_normalized', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('language', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_fact_checks_source_id_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fact_checks')),
    sa.UniqueConstraint('url', name=op.f('uq_fact_checks_url'))
    )
    op.create_table('source_ownership',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('owner_name', sa.Text(), nullable=False),
    sa.Column('owner_type', sa.Text(), nullable=True),
    sa.Column('parent_group', sa.Text(), nullable=True),
    sa.Column('evidence_url', sa.Text(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_by', sa.Text(), nullable=True),
    sa.Column('confidence', postgresql.ENUM('low', 'medium', 'high', name='confidence', create_type=False), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_source_ownership_source_id_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_ownership'))
    )
    op.create_table('source_ratings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('dimension', sa.Text(), nullable=False),
    sa.Column('rater', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('numeric_value', sa.REAL(), nullable=True),
    sa.Column('method_url', sa.Text(), nullable=False),
    sa.Column('evidence_url', sa.Text(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confidence', postgresql.ENUM('low', 'medium', 'high', name='confidence', create_type=False), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_source_ratings_source_id_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_ratings'))
    )
    op.create_index(op.f('ix_source_ratings_source_id_dimension'), 'source_ratings', ['source_id', 'dimension'], unique=False)
    op.create_table('story_stats',
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stance_counts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('factuality_counts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ownership_counts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('language_counts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('coverage_confidence', postgresql.ENUM('low', 'medium', 'high', name='confidence', create_type=False), nullable=False),
    sa.Column('blindspot_type', sa.Text(), nullable=True),
    sa.Column('blindspot_skew', sa.Text(), nullable=True),
    sa.Column('blindspot_score', sa.REAL(), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], name=op.f('fk_story_stats_story_id_stories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('story_id', name=op.f('pk_story_stats'))
    )
    op.create_table('story_summaries',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('lang', sa.Text(), nullable=False),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('agreements', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('disagreements', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('prompt_version', sa.Text(), nullable=False),
    sa.Column('verifier_result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], name=op.f('fk_story_summaries_story_id_stories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_story_summaries')),
    sa.UniqueConstraint('story_id', 'version', 'lang', name=op.f('uq_story_summaries_story_id_version_lang'))
    )
    op.create_table('story_views',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('story_version_seen', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], name=op.f('fk_story_views_story_id_stories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_story_views_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_story_views'))
    )
    op.create_table('user_preferences',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_preferences_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'key', name=op.f('pk_user_preferences'))
    )
    op.create_table('chunks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=False),
    sa.Column('char_end', sa.Integer(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('qdrant_point_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_chunks_article_id_articles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chunks')),
    sa.UniqueConstraint('article_id', 'idx', name=op.f('uq_chunks_article_id_idx'))
    )
    op.create_table('claims',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source_quote', sa.Text(), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=False),
    sa.Column('char_end', sa.Integer(), nullable=False),
    sa.Column('attributed_to', sa.Text(), nullable=True),
    sa.Column('checkable', sa.Boolean(), nullable=False),
    sa.Column('schema_version', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_claims_article_id_articles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claims'))
    )
    op.create_table('framings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('headline_framing', sa.Text(), nullable=False),
    sa.Column('tone', sa.Text(), nullable=False),
    sa.Column('stance_target', postgresql.ENUM('central_govt', 'state_govt', 'opposition', 'none', name='stance_target', create_type=False), nullable=False),
    sa.Column('stance', postgresql.ENUM('critical', 'balanced', 'supportive', 'not_applicable', 'unclassified', name='stance', create_type=False), nullable=False),
    sa.Column('stance_confidence', postgresql.ENUM('low', 'medium', 'high', name='confidence', create_type=False), nullable=False),
    sa.Column('emphasized', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('omitted_vs_others', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('prompt_version', sa.Text(), nullable=False),
    sa.Column('schema_version', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_framings_article_id_articles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], name=op.f('fk_framings_story_id_stories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_framings')),
    sa.UniqueConstraint('article_id', 'story_id', name=op.f('uq_framings_article_id_story_id'))
    )
    op.create_table('story_articles',
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('similarity', sa.REAL(), nullable=True),
    sa.Column('method', sa.Text(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_story_articles_article_id_articles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], name=op.f('fk_story_articles_story_id_stories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('story_id', 'article_id', name=op.f('pk_story_articles'))
    )
    op.create_table('claim_fact_check_matches',
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('fact_check_id', sa.UUID(), nullable=False),
    sa.Column('similarity', sa.REAL(), nullable=False),
    sa.Column('verdict', sa.Text(), nullable=False),
    sa.Column('verified_by_llm', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name=op.f('fk_claim_fact_check_matches_claim_id_claims'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fact_check_id'], ['fact_checks.id'], name=op.f('fk_claim_fact_check_matches_fact_check_id_fact_checks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('claim_id', 'fact_check_id', name=op.f('pk_claim_fact_check_matches'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('claim_fact_check_matches')
    op.drop_table('story_articles')
    op.drop_table('framings')
    op.drop_table('claims')
    op.drop_table('chunks')
    op.drop_table('user_preferences')
    op.drop_table('story_views')
    op.drop_table('story_summaries')
    op.drop_table('story_stats')
    op.drop_index(op.f('ix_source_ratings_source_id_dimension'), table_name='source_ratings')
    op.drop_table('source_ratings')
    op.drop_table('source_ownership')
    op.drop_table('fact_checks')
    op.drop_table('ask_turns')
    op.drop_index('ix_articles_source_id_published_at', table_name='articles')
    op.drop_index(op.f('ix_articles_simhash'), table_name='articles')
    op.drop_index('ix_articles_published_at', table_name='articles')
    op.drop_table('articles')
    op.drop_table('users')
    op.drop_index('ix_stories_topic_last_updated_at', table_name='stories')
    op.drop_index('ix_stories_last_updated_at', table_name='stories')
    op.drop_table('stories')
    op.drop_table('sources')
    op.drop_table('review_queue')
    op.drop_index('ix_guard_events_guard_id_created_at', table_name='guard_events')
    op.drop_table('guard_events')
    op.drop_table('feedback')
    op.drop_table('dead_letters')
    # ### end Alembic commands ###
    bind = op.get_bind()
    for name in ENUMS:
        postgresql.ENUM(name=name).drop(bind, checkfirst=True)
