/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness only. Does not check downstream services.
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Feed */
        get: operations["feed_api_v1_feed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stories/{id_or_slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Story */
        get: operations["story_api_v1_stories__id_or_slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stories/{id_or_slug}/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Story Articles */
        get: operations["story_articles_api_v1_stories__id_or_slug__articles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/blindspots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Blindspots */
        get: operations["blindspots_api_v1_blindspots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Topics */
        get: operations["topics_api_v1_topics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sources */
        get: operations["sources_api_v1_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/{id_or_slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Source */
        get: operations["source_api_v1_sources__id_or_slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/methodology": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Methodology */
        get: operations["methodology_api_v1_methodology_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask */
        post: operations["ask_api_v1_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/sources/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Sources
         * @description Body: the CSV itself (Content-Type: text/csv). Columns: see lens.ingest.source_import.
         */
        post: operations["import_sources_api_v1_admin_sources_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/review-queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Review Queue
         * @description Held story summaries (G-OUT-07), oldest first.
         */
        get: operations["review_queue_api_v1_admin_review_queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/review-queue/{item_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve Review */
        post: operations["resolve_review_api_v1_admin_review_queue__item_id__resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness only. Does not check downstream services.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ArticleRow */
        ArticleRow: {
            /** Id */
            id: string;
            source: components["schemas"]["ArticleSource"];
            /** Headline */
            headline: string;
            /** Headline Lang */
            headline_lang: string;
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
            /** Url */
            url: string;
            /**
             * Analysis Depth
             * @enum {string}
             */
            analysis_depth: "headline_only" | "snippet" | "full_text";
            /**
             * Bias
             * @enum {string}
             */
            bias: "left" | "center" | "right" | "unrated";
            source_bias: components["schemas"]["RatingRef"] | null;
            source_factuality: components["schemas"]["RatingRef"] | null;
            source_ownership: components["schemas"]["SourceOwnershipRef"] | null;
            /** Is Syndicated */
            is_syndicated: boolean;
            /** Also Carried By */
            also_carried_by: string[];
        };
        /** ArticleSource */
        ArticleSource: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Logo Url */
            logo_url: string | null;
            /** Language */
            language: string;
        };
        /** AskAbstain */
        AskAbstain: {
            /**
             * Reason
             * @enum {string}
             */
            reason: "insufficient_coverage" | "out_of_scope" | "sensitive_topic_under_review" | "guard_block" | "service_unavailable";
            /** Message */
            message: string;
            /** Closest Stories */
            closest_stories: components["schemas"]["StoryCard"][];
        };
        /**
         * AskAnswer
         * @description `answer_final`. Every sentence is cited and passed the checks; coverage is computed by code.
         *     `basis` is "stored_summary" when the live answer failed verification and the story's stored,
         *     already-verified summary is served instead (docs/06 fallback_precomputed).
         */
        AskAnswer: {
            /**
             * Basis
             * @enum {string}
             */
            basis: "live" | "stored_summary";
            /** Lang */
            lang: string;
            /** Tldr */
            tldr: components["schemas"]["CitedSentence"][];
            /** What Happened */
            what_happened: components["schemas"]["CitedSentence"][];
            /** Agreements */
            agreements: components["schemas"]["CitedSentence"][];
            /** Disagreements */
            disagreements: components["schemas"]["CitedSentence"][];
            /** Premises Addressed */
            premises_addressed: components["schemas"]["CitedSentence"][];
            /** Limitations */
            limitations: string[];
            /** Follow Up Questions */
            follow_up_questions: string[];
            /** Coverage */
            coverage: components["schemas"]["CoverageAvailable"] | components["schemas"]["CoverageLimited"];
            /** Fact Checks */
            fact_checks: components["schemas"]["FactCheckRef"][];
            /** Story Ids */
            story_ids: string[];
            /** Articles */
            articles: components["schemas"]["AskArticle"][];
            /**
             * Verified
             * @constant
             */
            verified: true;
        };
        /**
         * AskArticle
         * @description A cited article, so citation chips can show the headline and link (docs/09).
         */
        AskArticle: {
            /** Id */
            id: string;
            /** Headline */
            headline: string;
            /** Headline Lang */
            headline_lang: string;
            /** Url */
            url: string;
            /** Source Name */
            source_name: string;
            /** Source Language */
            source_language: string;
        };
        /** AskError */
        AskError: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Retry After S */
            retry_after_s?: number | null;
        };
        /**
         * AskEvents
         * @description Documentation only: the payload type of each `/ask` SSE event, keyed by event name, so the
         *     generated client has these types. The endpoint streams them as `event: <name>` / `data: <json>`.
         */
        AskEvents: {
            status: components["schemas"]["AskStatus"];
            understanding: components["schemas"]["AskUnderstanding"];
            evidence: components["schemas"]["AskEvidence"];
            answer_final: components["schemas"]["AskAnswer"];
            abstain: components["schemas"]["AskAbstain"];
            error: components["schemas"]["AskError"];
        };
        /** AskEvidence */
        AskEvidence: {
            /** Story Ids */
            story_ids: string[];
            /** Sources */
            sources: components["schemas"]["AskSource"][];
            /** Stale */
            stale: boolean;
            /** Newest Article At */
            newest_article_at: string | null;
            /** Methodology Url */
            methodology_url: string;
        };
        /** AskRequest */
        AskRequest: {
            /** Query */
            query: string;
            /** Session Id */
            session_id?: string | null;
            /** Lang */
            lang?: string | null;
        };
        /** AskSource */
        AskSource: {
            /** Source Id */
            source_id: string;
            /** Name */
            name: string;
            /** Language */
            language: string;
            /**
             * Bias
             * @enum {string}
             */
            bias: "left" | "center" | "right" | "unrated";
        };
        /** AskStatus */
        AskStatus: {
            /**
             * Step
             * @enum {string}
             */
            step: "understanding" | "searching" | "checking_sources" | "writing" | "verifying";
            /** Message */
            message: string;
        };
        /** AskUnderstanding */
        AskUnderstanding: {
            /** Neutral Query */
            neutral_query: string;
            /** Removed Premises */
            removed_premises: string[];
            /** Language */
            language: string;
            /** Intent */
            intent: string;
        };
        /** BiasBlindspot */
        BiasBlindspot: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "bias";
            /**
             * Skew
             * @enum {string}
             */
            skew: "left" | "center" | "right";
            /** Score */
            score: number;
        };
        /** Blindspots */
        Blindspots: {
            /**
             * Type
             * @enum {string}
             */
            type: "bias" | "language";
            /** Items */
            items: components["schemas"]["StoryCard"][];
            /** Methodology Url */
            methodology_url: string;
        };
        /** Citation */
        Citation: {
            /** N */
            n: number;
            /** Article Id */
            article_id: string;
            /** Source Name */
            source_name: string;
            /** Chunk Id */
            chunk_id: string;
        };
        /** CitedSentence */
        CitedSentence: {
            /** Text */
            text: string;
            /** Citations */
            citations: components["schemas"]["Citation"][];
        };
        /** Counts */
        Counts: {
            /** Sources */
            sources: number;
            /** Articles */
            articles: number;
            /** By Language */
            by_language: {
                [key: string]: number;
            };
        };
        /** CoverageAvailable */
        CoverageAvailable: {
            /**
             * Available
             * @default true
             * @constant
             */
            available: true;
            /**
             * Basis
             * @default outlet_bias
             * @constant
             */
            basis: "outlet_bias";
            /** Buckets */
            buckets: components["schemas"]["CoverageBucket"][];
            unrated: components["schemas"]["SourcesPct"];
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "low" | "medium" | "high";
            /** Methodology Url */
            methodology_url: string;
        };
        /** CoverageBucket */
        CoverageBucket: {
            /**
             * Key
             * @enum {string}
             */
            key: "left" | "center" | "right";
            /** Sources */
            sources: number;
            /** Pct */
            pct: number;
        };
        /** CoverageLimited */
        CoverageLimited: {
            /**
             * Available
             * @default false
             * @constant
             */
            available: false;
            /**
             * Reason
             * @default limited_coverage
             * @constant
             */
            reason: "limited_coverage";
            /** Min Sources */
            min_sources: number;
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "low" | "medium" | "high";
            /** Methodology Url */
            methodology_url: string;
        };
        /** ErrorBody */
        ErrorBody: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Retry After S */
            retry_after_s?: number | null;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        /**
         * FactCheckRef
         * @description A fact-checker's published verdict, never ours (docs/13): their name, their wording, their link.
         */
        FactCheckRef: {
            /** Claim */
            claim: string;
            /** Fact Checker */
            fact_checker: string;
            /**
             * Rating
             * @description The fact-checker's own rating wording
             */
            rating: string;
            /**
             * Rating Normalized
             * @enum {string}
             */
            rating_normalized: "true" | "false" | "misleading" | "unproven" | "other";
            /**
             * Match
             * @description same_claim: this fact-check examines the claim; related: same event, different claim
             * @enum {string}
             */
            match: "same_claim" | "related";
            /** Url */
            url: string;
            /** Published At */
            published_at: string | null;
        };
        /** FactualityCounts */
        FactualityCounts: {
            /** High */
            high: number;
            /** Mixed */
            mixed: number;
            /** Low */
            low: number;
            /** Unrated */
            unrated: number;
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "low" | "medium" | "high";
            /** Methodology Url */
            methodology_url: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
            /** Env */
            env: string;
        };
        /** LanguageBlindspot */
        LanguageBlindspot: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "language";
            /** Skew */
            skew: string;
            /** Score */
            score: number;
        };
        /** Methodology */
        Methodology: {
            /** Min Sources For Bar */
            min_sources_for_bar: number;
            /** Min Sources For Blindspot */
            min_sources_for_blindspot: number;
            /** Blindspot Bias Share */
            blindspot_bias_share: number;
            /** Blindspot Language Share */
            blindspot_language_share: number;
            /** Feed Min Sources */
            feed_min_sources: number;
            /** Raters */
            raters: components["schemas"]["Rater"][];
        };
        /** Ownership */
        Ownership: {
            /** Groups */
            groups: components["schemas"]["OwnershipGroup"][];
            /** Unknown */
            unknown: number;
            /** Methodology Url */
            methodology_url: string;
        };
        /** OwnershipGroup */
        OwnershipGroup: {
            /** Name */
            name: string;
            /** Sources */
            sources: number;
        };
        /** OwnershipRecord */
        OwnershipRecord: {
            /** Owner Name */
            owner_name: string;
            /** Owner Type */
            owner_type: string | null;
            /** Parent Group */
            parent_group: string | null;
            /** Evidence Url */
            evidence_url: string;
            /**
             * Retrieved At
             * Format: date-time
             */
            retrieved_at: string;
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "low" | "medium" | "high";
        };
        /** Rater */
        Rater: {
            /** Rater */
            rater: string;
            /** Dimension */
            dimension: string;
            /** Method Url */
            method_url: string;
            /** Sources Rated */
            sources_rated: number;
        };
        /** RatingRecord */
        RatingRecord: {
            /** Dimension */
            dimension: string;
            /** Rater */
            rater: string;
            /** Value */
            value: string;
            /** Method Url */
            method_url: string;
            /** Evidence Url */
            evidence_url: string | null;
            /**
             * Retrieved At
             * Format: date-time
             */
            retrieved_at: string;
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "low" | "medium" | "high";
        };
        /**
         * RatingRef
         * @description An outlet rating as shown on an article row: "According to {rater}: {value}".
         */
        RatingRef: {
            /** Rater */
            rater: string;
            /** Value */
            value: string;
            /** Method Url */
            method_url: string;
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "low" | "medium" | "high";
        };
        /** Resolved */
        Resolved: {
            /**
             * Status
             * @enum {string}
             */
            status: "approved" | "rejected";
        };
        /** SourceDetail */
        SourceDetail: {
            source: components["schemas"]["SourceSummary"];
            /** Ownership */
            ownership: components["schemas"]["OwnershipRecord"][];
            /** Ratings */
            ratings: components["schemas"]["RatingRecord"][];
            /** Recent Stories */
            recent_stories: components["schemas"]["StoryCard"][];
            /** Methodology Url */
            methodology_url: string;
        };
        /** SourceImportResult */
        SourceImportResult: {
            /** Ownership Added */
            ownership_added: number;
            /** Ratings Added */
            ratings_added: number;
            /** Unchanged */
            unchanged: number;
        };
        /** SourceList */
        SourceList: {
            /** Items */
            items: components["schemas"]["SourceSummary"][];
        };
        /** SourceOwnershipRef */
        SourceOwnershipRef: {
            /** Owner */
            owner: string;
            /** Evidence Url */
            evidence_url: string;
        };
        /** SourceSummary */
        SourceSummary: {
            /** Id */
            id: string;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Homepage Url */
            homepage_url: string;
            /** Languages */
            languages: string[];
            /** Region */
            region: string | null;
            /** Is Wire */
            is_wire: boolean;
            /**
             * License Mode
             * @enum {string}
             */
            license_mode: "full_text" | "snippet_only" | "link_only";
        };
        /** SourcesPct */
        SourcesPct: {
            /** Sources */
            sources: number;
            /** Pct */
            pct: number;
        };
        /** StoryArticles */
        StoryArticles: {
            /** Items */
            items: components["schemas"]["ArticleRow"][];
            /** Methodology Url */
            methodology_url: string;
        };
        /** StoryCard */
        StoryCard: {
            /** Id */
            id: string;
            /** Slug */
            slug: string;
            /** Headline */
            headline: string;
            /** Headline Lang */
            headline_lang: string;
            /**
             * Status
             * @enum {string}
             */
            status: "developing" | "stable" | "archived";
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Topic */
            topic: string | null;
            image: components["schemas"]["StoryImage"] | null;
            counts: components["schemas"]["Counts"];
            /** Coverage */
            coverage: components["schemas"]["CoverageAvailable"] | components["schemas"]["CoverageLimited"];
            factuality: components["schemas"]["FactualityCounts"];
            /** Blindspot */
            blindspot: (components["schemas"]["BiasBlindspot"] | components["schemas"]["LanguageBlindspot"]) | null;
            /** Summary Preview */
            summary_preview: string | null;
        };
        /** StoryCardPage */
        StoryCardPage: {
            /** Items */
            items: components["schemas"]["StoryCard"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** StoryDetail */
        StoryDetail: {
            story: components["schemas"]["StoryCard"];
            summary: components["schemas"]["StorySummary"] | null;
            /** Framing Differences */
            framing_differences: components["schemas"]["CitedSentence"][];
            /** Fact Checks */
            fact_checks: components["schemas"]["FactCheckRef"][];
            ownership: components["schemas"]["Ownership"];
            /** Limitations */
            limitations: string[];
        };
        /** StoryImage */
        StoryImage: {
            /** Url */
            url: string;
            /** Source Name */
            source_name: string;
        };
        /** StorySummary */
        StorySummary: {
            /** Lang */
            lang: string;
            /** Version */
            version: number;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Verified */
            verified: boolean;
            /** Sentences */
            sentences: components["schemas"]["CitedSentence"][];
            /** Agreements */
            agreements: components["schemas"]["CitedSentence"][];
            /** Disagreements */
            disagreements: components["schemas"]["CitedSentence"][];
        };
        /** Topic */
        Topic: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
        };
        /** Topics */
        Topics: {
            /** Items */
            items: components["schemas"]["Topic"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    feed_api_v1_feed_get: {
        parameters: {
            query?: {
                tab?: "home" | "blindspot" | "local";
                topic?: string | null;
                state?: string | null;
                lang?: string | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoryCardPage"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    story_api_v1_stories__id_or_slug__get: {
        parameters: {
            query?: {
                lang?: string | null;
            };
            header?: never;
            path: {
                id_or_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoryDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    story_articles_api_v1_stories__id_or_slug__articles_get: {
        parameters: {
            query?: {
                group?: "bias" | "language" | "all";
                bias?: ("left" | "center" | "right" | "unrated") | null;
                lang?: string | null;
            };
            header?: never;
            path: {
                id_or_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoryArticles"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    blindspots_api_v1_blindspots_get: {
        parameters: {
            query?: {
                type?: "bias" | "language";
                lang?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Blindspots"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    topics_api_v1_topics_get: {
        parameters: {
            query?: {
                lang?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Topics"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sources_api_v1_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceList"];
                };
            };
        };
    };
    source_api_v1_sources__id_or_slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id_or_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    methodology_api_v1_methodology_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Methodology"];
                };
            };
        };
    };
    ask_api_v1_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description SSE stream; payload type per event name (docs/09) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["AskEvents"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    import_sources_api_v1_admin_sources_import_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "text/csv": string;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceImportResult"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    review_queue_api_v1_admin_review_queue_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: {
                            [key: string]: unknown;
                        }[];
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_review_api_v1_admin_review_queue__item_id__resolve_post: {
        parameters: {
            query: {
                decision: "approve" | "reject";
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resolved"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
}
